# Generated by Django 5.2.6 on 2025-09-22 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('type', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=20)),
                ('duration', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuizApp.quizcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_corrected', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QuizApp.quizquestions')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('time_taken', models.TimeField()),
                ('date', models.DateField(auto_now=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('totalCorrect', models.IntegerField(default=0)),
                ('totalWrong', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertype', to='QuizApp.quizcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userscore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spend', models.TimeField()),
                ('average_score', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBoard', to=settings.AUTH_USER_MODEL)),
                ('user_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='QuizApp.userscore')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('correct_ans', models.TextField()),
                ('is_corrected', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionSubmission', to='QuizApp.quizquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubmission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
