# Generated by Django 5.2.6 on 2025-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='time_taken',
            field=models.FloatField(),
        ),
    ]
